version = 0.1

[default.deploy.parameters]
stack_name = "serverless-social-media"
resolve_s3 = true
s3_prefix = "serverless-social-media"
region = "eu-north-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "CognitoUserPoolId=\"eu-north-1_RFZvLrDd9\" CognitoClientId=\"1cvth0disa6uhcgflcsih54hfl\" S3BucketName=\"serverless-social-media-storage-123\" CloudFrontDomain=\"dsvtq5o5a0ykh.cloudfront.net\" Environment=\"prod\""
image_repositories = []
