AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless Social Media Application

Parameters:
  CognitoUserPoolId:
    Type: String
    Default: eu-north-1_RFZvLrDd9
  CognitoClientId:
    Type: String
    Default: 7p0e3uioc8mtq69m4qq12540mn
  S3BucketName:
    Type: String
    Default: serverless-social-media-storage-123
  CloudFrontDomain:
    Type: String
    Default: dsvtq5o5a0ykh.cloudfront.net
  Environment:
    Type: String
    Default: prod

Conditions:
  IsLocal: !Equals [!Ref Environment, "local"]

Globals:
  Function:
    Timeout: 30
    Runtime: nodejs18.x
    Environment:
      Variables:
        COGNITO_USER_POOL_ID: !Ref CognitoUserPoolId
        COGNITO_CLIENT_ID: !Ref CognitoClientId
        S3_BUCKET_NAME: !Ref S3BucketName
        CLOUDFRONT_DOMAIN: !Ref CloudFrontDomain
        USERS_TABLE: !Ref UsersTable
        POSTS_TABLE: !Ref PostsTable
        LOOPS_TABLE: !Ref LoopsTable
        STORIES_TABLE: !Ref StoriesTable
        MESSAGES_TABLE: !Ref MessagesTable
        CONVERSATIONS_TABLE: !Ref ConversationsTable
        NOTIFICATIONS_TABLE: !Ref NotificationsTable
        CONNECTIONS_TABLE: !Ref ConnectionsTable

Resources:
  # DynamoDB Tables
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Users
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: email
          AttributeType: S
        - AttributeName: userName
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: email-index
          KeySchema:
            - AttributeName: email
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: userName-index
          KeySchema:
            - AttributeName: userName
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  PostsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Posts
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: postId
          AttributeType: S
        - AttributeName: authorId
          AttributeType: S
      KeySchema:
        - AttributeName: postId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: author-index
          KeySchema:
            - AttributeName: authorId
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  LoopsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Loops
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: loopId
          AttributeType: S
        - AttributeName: authorId
          AttributeType: S
      KeySchema:
        - AttributeName: loopId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: author-index
          KeySchema:
            - AttributeName: authorId
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  StoriesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Stories
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: storyId
          AttributeType: S
        - AttributeName: authorId
          AttributeType: S
      KeySchema:
        - AttributeName: storyId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: author-index
          KeySchema:
            - AttributeName: authorId
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  MessagesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Messages
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: messageId
          AttributeType: S
        - AttributeName: conversationId
          AttributeType: S
      KeySchema:
        - AttributeName: messageId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: conversation-index
          KeySchema:
            - AttributeName: conversationId
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  ConversationsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Conversations
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: conversationId
          AttributeType: S
        - AttributeName: participant1
          AttributeType: S
        - AttributeName: participant2
          AttributeType: S
      KeySchema:
        - AttributeName: conversationId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: participant1-index
          KeySchema:
            - AttributeName: participant1
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: participant2-index
          KeySchema:
            - AttributeName: participant2
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  NotificationsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Notifications
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: notificationId
          AttributeType: S
        - AttributeName: receiverId
          AttributeType: S
      KeySchema:
        - AttributeName: notificationId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: receiver-index
          KeySchema:
            - AttributeName: receiverId
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  ConnectionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Connections
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: connectionId
          AttributeType: S
      KeySchema:
        - AttributeName: connectionId
          KeyType: HASH

  # API Gateway
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
      Auth:
        DefaultAuthorizer: !If [IsLocal, MockAuthorizer, CognitoUserPoolAuthorizer]
        Authorizers:
          CognitoUserPoolAuthorizer:
            UserPoolArn: !Sub arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${CognitoUserPoolId}
          MockAuthorizer:
            FunctionArn: !GetAtt MockAuthorizer.Arn

  # Mock Authorizer for Local Testing
  MockAuthorizer:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: mock/
      Handler: mockAuthorizer.handler
      Runtime: nodejs18.x

  # Auth Functions (No Auth Required)
  AuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/functions/auth/
      Handler: index.handler
      Events:
        SignUp:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /api/auth/signup
            Method: post
            Auth:
              Authorizer: NONE
        SignIn:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /api/auth/signin
            Method: post
            Auth:
              Authorizer: NONE
        SignOut:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /api/auth/signout
            Method: get
            Auth:
              Authorizer: NONE
        ForgotPassword:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /api/auth/forgot-password
            Method: post
            Auth:
              Authorizer: NONE
        ResetPassword:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /api/auth/reset-password
            Method: post
            Auth:
              Authorizer: NONE
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - cognito-idp:*
              Resource: '*'

  # User Functions
  UserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/functions/user/
      Handler: index.handler
      Events:
        GetCurrentUser:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /api/user/current
            Method: get
        GetProfile:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /api/user/getProfile/{userName}
            Method: get
        EditProfile:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /api/user/editProfile
            Method: post
        Follow:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /api/user/follow/{userId}
            Method: get
        GetSuggested:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /api/user/suggested
            Method: get
        Search:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /api/user/search
            Method: get
        GetFollowing:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /api/user/followingList
            Method: get
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
        - DynamoDBCrudPolicy:
            TableName: !Ref PostsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref NotificationsTable
        - S3CrudPolicy:
            BucketName: !Ref S3BucketName

  # Post Functions
  PostFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/functions/post/
      Handler: index.handler
      Events:
        Upload:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /api/post/upload
            Method: post
        GetAll:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /api/post/getAll
            Method: get
        Like:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /api/post/like/{postId}
            Method: get
        Comment:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /api/post/comment/{postId}
            Method: post
        Saved:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /api/post/saved/{postId}
            Method: get
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PostsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
        - DynamoDBCrudPolicy:
            TableName: !Ref NotificationsTable
        - S3CrudPolicy:
            BucketName: !Ref S3BucketName

  # Loop Functions
  LoopFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/functions/loop/
      Handler: index.handler
      Events:
        Upload:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /api/loop/upload
            Method: post
        GetAll:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /api/loop/getAll
            Method: get
        Like:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /api/loop/like/{loopId}
            Method: get
        Comment:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /api/loop/comment/{loopId}
            Method: post
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref LoopsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
        - DynamoDBCrudPolicy:
            TableName: !Ref NotificationsTable

  # Story Functions
  StoryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/functions/story/
      Handler: index.handler
      Events:
        Upload:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /api/story/upload
            Method: post
        GetAll:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /api/story/getAll
            Method: get
        GetByUserName:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /api/story/getByUserName/{userName}
            Method: get
        View:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /api/story/view/{storyId}
            Method: get
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref StoriesTable
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable

  # Message Functions
  MessageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/functions/message/
      Handler: index.handler
      Events:
        Send:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /api/message/send/{userId}
            Method: post
        GetAll:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /api/message/getAll/{userId}
            Method: get
        GetPrevChats:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /api/message/prevChats
            Method: get
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MessagesTable
        - DynamoDBCrudPolicy:
            TableName: !Ref ConversationsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable

  # Notification Functions
  NotificationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/functions/notification/
      Handler: index.handler
      Events:
        GetAll:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /api/user/getAllNotifications
            Method: get
        MarkAsRead:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /api/user/markAsRead
            Method: post
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref NotificationsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
        - DynamoDBCrudPolicy:
            TableName: !Ref PostsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref LoopsTable

  # Media Functions
  MediaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/functions/media/
      Handler: index.handler
      Events:
        GetPresignedUrl:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /api/media/presigned-url
            Method: post
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref S3BucketName

  # WebSocket API
  WebSocketApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: SocialMediaWebSocket
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: "$request.body.action"

  # WebSocket Functions
  WebSocketConnectFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/functions/websocket/
      Handler: connect.handler
      Environment:
        Variables:
          WEBSOCKET_API_ID: !Ref WebSocketApi
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ConnectionsTable

  WebSocketDisconnectFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/functions/websocket/
      Handler: disconnect.handler
      Environment:
        Variables:
          WEBSOCKET_API_ID: !Ref WebSocketApi
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ConnectionsTable

  WebSocketMessageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/functions/websocket/
      Handler: message.handler
      Environment:
        Variables:
          WEBSOCKET_API_ID: !Ref WebSocketApi
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ConnectionsTable
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - execute-api:ManageConnections
              Resource: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WebSocketApi}/*'

  # WebSocket Routes
  ConnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketApi
      RouteKey: $connect
      AuthorizationType: NONE
      Target: !Sub 'integrations/${ConnectIntegration}'

  DisconnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketApi
      RouteKey: $disconnect
      AuthorizationType: NONE
      Target: !Sub 'integrations/${DisconnectIntegration}'

  MessageRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketApi
      RouteKey: message
      AuthorizationType: NONE
      Target: !Sub 'integrations/${MessageIntegration}'

  # WebSocket Integrations
  ConnectIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocketApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WebSocketConnectFunction.Arn}/invocations'

  DisconnectIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocketApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WebSocketDisconnectFunction.Arn}/invocations'

  MessageIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocketApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WebSocketMessageFunction.Arn}/invocations'

  # WebSocket Deployment
  WebSocketDeployment:
    Type: AWS::ApiGatewayV2::Deployment
    DependsOn:
      - ConnectRoute
      - DisconnectRoute
      - MessageRoute
    Properties:
      ApiId: !Ref WebSocketApi

  WebSocketStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref WebSocketApi
      DeploymentId: !Ref WebSocketDeployment
      StageName: prod

  # Lambda Permissions for WebSocket
  WebSocketConnectPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref WebSocketConnectFunction
      Principal: apigateway.amazonaws.com

  WebSocketDisconnectPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref WebSocketDisconnectFunction
      Principal: apigateway.amazonaws.com

  WebSocketMessagePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref WebSocketMessageFunction
      Principal: apigateway.amazonaws.com

Outputs:
  ApiGatewayUrl:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/prod'
    Export:
      Name: !Sub '${AWS::StackName}-ApiGatewayUrl'
  
  WebSocketUrl:
    Description: WebSocket API endpoint URL
    Value: !Sub 'wss://${WebSocketApi}.execute-api.${AWS::Region}.amazonaws.com/prod'
    Export:
      Name: !Sub '${AWS::StackName}-WebSocketUrl'